services:
   base-data-retriever:
      build: base_data_retriever/.

      environment:
         - LOG_LEVEL=INFO

      env_file:
         - sp/az_msi_local.env

      ports:
         - "8003:80"
      volumes:
         - cache-vol:/base_data_retriever/cache

   data-transformer:
      build: views_transform/.

      environment:
         - REST_ENV_URL=http://mock-config
         - LOG_LEVEL=DEBUG

         - ROUTER_URL=http://router

      env_file:
         - sp/az_msi_local.env

      ports:
         - "8002:80"

   router:
      build: views_router/.

      environment:
         - REST_ENV_URL=http://mock-config
         - LOG_LEVEL=INFO
         - BASE_DATA_RETRIEVER_URL=http://base-data-retriever
         - TRANSFORMER_URL=http://data-transformer

      env_file:
         - sp/az_msi_local.env

      ports:
         - "8001:80"
      volumes:
         - cache-vol:/views_data_router/cache

   job-manager:
      build: views_job_manager/.

      environment: 
         - LOG_LEVEL=INFO
         - ROUTER_URL=http://router

      env_file:
         - sp/az_msi_local.env

      ports:
         - "8000:80"
      volumes:
         - cache-vol:/views_job_manager/cache

   queryset-manager:
      build: "views_queryset_manager/."

      environment:
         - SOURCE_URL=http://job-manager
         - LOG_LEVEL=INFO

      env_file:
         - sp/az_msi_local.env

      ports:
         - "7999:80"
volumes:
   cache-vol:
