version: "3.9"
services:
   seclevel-fixer:
      image: alpine/openssl
      entrypoint:  ["sed", "-i", "s/SECLEVEL=[0-9]/SECLEVEL=1/g", "/etc/ssl/openssl.cnf"]
      volumes:
         - openssl-conf:/etc/ssl/

   certificate-permissions:
     image: bash:5.1.16 
     entrypoint: ["bash", "-c", "cp /mnt/certs/* /mnt/fixed && chown -R 1005:1005 /mnt/fixed"]
     volumes:
        - ~/.postgresql:/mnt/certs:ro
        - certs:/mnt/fixed:rw

   storefront:
      image: views3/storefront:2.0.1

      env_file:
         - services.env

      ports:
         - "4000:80"
      networks:
         - backend

      depends_on:
         - certificate-permissions
         - queryset-manager

      restart: always


   queryset-manager:
      image: views3/queryset-manager:4.2.1

      environment:
         QUERYSET_MANAGER_DB_HOST: $QUERYSET_MANAGER_DB_HOST
         QUERYSET_MANAGER_DB_PORT: $QUERYSET_MANAGER_DB_PORT
         QUERYSET_MANAGER_DB_NAME: $QUERYSET_MANAGER_DB_NAME
         QUERYSET_MANAGER_DB_USER: $QUERYSET_MANAGER_DB_USER
         QUERYSET_MANAGER_DB_SSL: $QUERYSET_MANAGER_DB_SSL

         LOG_LEVEL: $LOG_LEVEL

      env_file:
         - gunicorn_config.env
         - services.env
         - config.env

      ports:
         - "4002:8080"

      volumes:
         - ./logs:/home/gunicorn/log
         - openssl-conf:/etc/ssl/
         - certs:/home/gunicorn/.postgresql:ro

      networks:
         - backend

      depends_on:
         - certificate-permissions
         - seclevel-fixer

      restart: always

volumes:
   certs:
   openssl-conf:

networks:
   backend:
      name: views_integration
