version: "3.9"
services:
   storefront:
      build: views_storefront/.
      image: prioreg.azurecr.io/views-storefront

      env_file:
         - services.env 

      ports:
         - "4000:80"
      networks:
         - backend

      depends_on:
         - docs
         - queryset-manager

   docs:
      build: views_docs/.
      image: prioreg.azurecr.io/views-docs
      environment:
         BASE_DATA_RETRIEVER_URL: http://base-data-retriever
         TRANSFORMER_URL: http://data-transformer
      env_file:
         - $AUTH_FILE
         - services.env
      ports:
         - "4001:80"
      networks:
         - backend

   queryset-manager:
      build: "views_queryset_manager/."
      image: prioreg.azurecr.io/views-queryset-manager

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4002:80"

      networks:
         - backend 

      depends_on:
         - job-manager

   job-manager:
      build: views_job_manager/.
      image: prioreg.azurecr.io/views-job-manager

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4003:80"

      volumes:
         - cache-vol:/views_job_manager/cache
      networks:
         - backend 

      depends_on:
         - router

   router:
      build: views_router/.
      image: prioreg.azurecr.io/views-router

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4004:80"

      volumes:
         - cache-vol:/views_data_router/cache
      networks:
         - backend 

      depends_on:
         - base-data-retriever
         - data-transformer

   base-data-retriever:
      build: base_data_retriever/.
      image: prioreg.azurecr.io/views-base-data-retriever

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4005:80"

      volumes:
         - cache-vol:/base_data_retriever/cache
      networks:
         - backend

   data-transformer:
      build: views_data_transformer/.
      image: prioreg.azurecr.io/views-data-transformer

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4006:80"

      networks:
         - backend 

volumes:
   cache-vol:

networks:
   backend:
      name: views-integration
