version: "3.9"
services:
   log_aggregator: 
      image: peder2911/logagg:1.0.0
      ports: 
         - "4008:80"
      volumes:
         - ./logs:/var/log/services

   storefront:
      image: viewsregistry.azurecr.io/prio-data/views_storefront:2.0.0

      env_file:
         - services.env 

      ports:
         - "4000:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar
         - docs
         - queryset-manager

      restart: always

   ssl-sidecar:
      image: prioreg.azurecr.io/prio-data/pg_ssl_sidecar:2.0.1
      env_file:
         - $AUTH_FILE
      environment:
         LOG_LEVEL: $LOG_LEVEL 
      volumes:
         - ./logs/ssl-sidecar:/var/log/app
         - home-vol:/home_mnt

   data-cache:
      image: prioreg.azurecr.io/prio-data/restblobs:1.1.0
      env_file:
         - $AUTH_FILE
      environment:
         CONTAINER_NAME: $CACHE_CONTAINER_NAME 
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/cache_access.log"
         ERROR_LOG_FILE: "/var/log/app/cache_error.log"
      ports:
         - "4007:80"
      networks:
         - backend 

      restart: always

   docs:
      image: viewsregistry.azurecr.io/prio-data/views_docs:2.1.0

      environment:
         DB_HOST: $DOCS_DB_HOST
         DB_PORT: $DOCS_DB_PORT
         DB_NAME: $DOCS_DB_NAME
         DB_USER: $DOCS_DB_USER
         DB_SSL: $DB_SSL

         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/docs_access.log"
         ERROR_LOG_FILE: "/var/log/app/docs_error.log"

      env_file:
         - $AUTH_FILE
         - services.env

      volumes:
         - ./logs:/var/log/app
         - home-vol:/root

      ports:
         - "4001:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar

      restart: always

   queryset-manager:
      image: viewsregistry.azurecr.io/prio-data/views_queryset_manager:2.1.0

      environment:
         DB_HOST: $QUERYSET_MANAGER_DB_HOST
         DB_PORT: $QUERYSET_MANAGER_DB_PORT
         DB_NAME: $QUERYSET_MANAGER_DB_NAME
         DB_USER: $QUERYSET_MANAGER_DB_USER
         DB_SSL: $DB_SSL
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/queryset_manager_access.log"
         ERROR_LOG_FILE: "/var/log/app/queryset_manager_error.log"

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4002:80"

      volumes:
         - ./logs:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - job-manager

      restart: always

   jobman-redis:
      image: redis
      networks:
         - backend

      restart: always

   job-manager:
      image: viewsregistry.azurecr.io/prio-data/views_job_manager:3.0.1

      environment:
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/job_manager_access.log"
         ERROR_LOG_FILE: "/var/log/app/job_manager_error.log"
        
     

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4003:80"

      volumes:
         - ./logs:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - router
         - ssl-sidecar
         - jobman-redis

      restart: always

   router:
      image: viewsregistry.azurecr.io/prio-data/views_router:3.1.0

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      environment:
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/router_access.log"
         ERROR_LOG_FILE: "/var/log/app/router_error.log"


      ports:
         - "4004:80"

      volumes:
         - ./logs:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - base-data-retriever
         - data-transformer

      restart: always

   base-data-retriever:
      image: viewsregistry.azurecr.io/prio-data/base_data_retriever:3.2.0

      environment:
         DB_HOST: $BASE_DB_HOST
         DB_PORT: $BASE_DB_PORT
         DB_NAME: $BASE_DB_NAME
         DB_USER: $BASE_DB_USER
         DB_SSL: $DB_SSL

         DB_SCHEMA: $BASE_DB_SCHEMA
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/base_data_retriever_access.log"
         ERROR_LOG_FILE: "/var/log/app/base_data_retriever_error.log"

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4005:80"

      volumes:
         - ./logs:/var/log/app
         - home-vol:/root

      networks:
         - backend

      restart: always

   data-transformer:
      image: viewsregistry.azurecr.io/prio-data/views_data_transformer:1.3.1

      environment:
         LOG_LEVEL: $LOG_LEVEL 
         ACCESS_LOG_FILE: "/var/log/app/data_transformer_access.log"
         ERROR_LOG_FILE: "/var/log/app/data_transformer_error.log"

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4006:80"

      networks:
         - backend 

      volumes:
         - ./logs:/var/log/app

      restart: always

volumes:
   home-vol:

networks:
   backend:
      name: views_integration
