version: "3.9"
services:
   seclevel-fixer:
      image: alpine/openssl
      entrypoint:  ["sed", "-i", "s/SECLEVEL=[0-9]/SECLEVEL=1/g", "/etc/ssl/openssl.cnf"]
      volumes:
         - openssl-conf:/etc/ssl/

   certificate-permissions:
     image: bash:5.1.16 
     entrypoint: ["bash", "-c", "cp /mnt/certs/* /mnt/fixed && chown -R 1005:1005 /mnt/fixed"]
     env_file:
       - gunicorn_config.env
     volumes:
        - ~/.postgresql:/mnt/certs:ro
        - certs:/mnt/fixed:rw

   storefront:
      image: views3/storefront:new_arch

      environment:
          QUERYSET_MANAGER_URL: $QUERYSET_MANAGER_URL
          DATA_SERVICE_URL: $DATA_SERVICE_URL

      ports:
         - "80:80"

      networks:
         - backend

      depends_on:
         - certificate-permissions
         - queryset-manager
         - data-service

      restart: always
      
   redis_db:
      image: redis
      networks:
         - backend

      restart: always
      
   queryset-manager:
      image: views3/queryset-manager:new_arch

      environment:
         QUERYSET_MANAGER_DB_HOST: $QUERYSET_MANAGER_DB_HOST
         QUERYSET_MANAGER_DB_PORT: $QUERYSET_MANAGER_DB_PORT
         QUERYSET_MANAGER_DB_NAME: $QUERYSET_MANAGER_DB_NAME
         QUERYSET_MANAGER_DB_USER: $QUERYSET_MANAGER_DB_USER
         QUERYSET_MANAGER_DB_SSL: $QUERYSET_MANAGER_DB_SSL

         DATA_SERVICE_URL: $DATA_SERVICE_URL

         LOG_LEVEL: $LOG_LEVEL

         LOGDIR: $LOGDIR

      env_file:
         - gunicorn_config.env

      expose:
         - "8080"

      volumes:
         - ./logs:$LOGDIR
         - openssl-conf:/etc/ssl/
         - certs:/home/gunicorn/.postgresql:ro

      networks:
         - backend

      depends_on:
         - certificate-permissions
         - seclevel-fixer

      restart: always

   data-service:
      image: views3/views_data_service:prod

      command: >
         bash -c "cd /views_data_service/
         && /home/gunicorn/.local/bin/celery -A celery_app worker --loglevel=INFO --logfile=/home/gunicorn/log/transform.log --detach -n worker_xform\%h --queues=transform
         && /home/gunicorn/.local/bin/celery -A celery_app worker --loglevel=INFO --logfile=/home/gunicorn/log/fetch.log --detach --pool=solo -n worker_fetch0\%h --queues=fetch0
         && /home/gunicorn/.local/bin/celery -A celery_app worker --loglevel=INFO --logfile=/home/gunicorn/log/fetch.log --detach --pool=solo -n worker_fetch1\%h --queues=fetch1
         && /home/gunicorn/.local/bin/celery -A celery_app worker --loglevel=INFO --logfile=/home/gunicorn/log/fetch.log --detach --pool=solo -n worker_fetch2\%h --queues=fetch2
         && /home/gunicorn/.local/bin/celery -A celery_app worker --loglevel=INFO --logfile=/home/gunicorn/log/fetch.log --detach --pool=solo -n worker_fetch3\%h --queues=fetch3
         && python3 -m gunicorn -c /home/gunicorn/gunicorn.conf.py
         && tail -f /dev/null"

      environment:

         DATA_SERVICE_DB_HOST: $DATA_SERVICE_DB_HOST
         DATA_SERVICE_DB_PORT: $DATA_SERVICE_DB_PORT
         DATA_SERVICE_DB_NAME: $DATA_SERVICE_DB_NAME
         DATA_SERVICE_DB_USER: $DATA_SERVICE_DB_USER
         DATA_SERVICE_DB_SSL: $DATA_SERVICE_DB_SSL
         DATA_SERVICE_DB_SCHEMA: $DATA_SERVICE_DB_SCHEMA

         LOG_LEVEL: $LOG_LEVEL
         LOGDIR: $LOGDIR
         CACHEDIR: $CACHEDIR
         GRAPHDIR: $GRAPHDIR

         REDIS_HOST: $REDIS_HOST
         REDIS_PORT: $REDIS_PORT
         REDIS_DB: $REDIS_DB

      env_file:
         - gunicorn_config.env

      expose:
         - "8080"

      volumes:
         - ./logs:$LOGDIR
         - ./cache:$CACHEDIR
         - ./graphs:$GRAPHDIR
         - openssl-conf:/etc/ssl/
         - certs:/home/gunicorn/.postgresql:ro
         - /home/views_data/.ingester3:/home/gunicorn/.ingester3

      networks:
         - backend

      depends_on:
         - certificate-permissions
         - seclevel-fixer
         - redis_db

      restart: always

volumes:
   certs:
   openssl-conf:

networks:
   backend:

