version: "3.9"
services:

   storefront:
      build: views_storefront/.
      image: viewsregistry.azurecr.io/prio-data/views_storefront:2.0.0

      env_file:
         - services.env 

      ports:
         - "4000:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar
         - docs
         - queryset-manager

   ssl-sidecar:
      image: prioreg.azurecr.io/prio-data/pg_ssl_sidecar:2.0.1
      env_file:
         - $AUTH_FILE
      volumes:
         - ./logs/ssl-sidecar:/var/log/app
         - home-vol:/home_mnt

   data-cache:
      image: prioreg.azurecr.io/prio-data/restblobs:1.0.0
      env_file:
         - $AUTH_FILE
      environment:
         CONTAINER_NAME: $CACHE_CONTAINER_NAME 
      ports:
         - "4007:80"
      networks:
         - backend 

   docs:
      build: views_docs/.
      image: viewsregistry.azurecr.io/prio-data/views_docs:2.0.0

      environment:
         DB_HOST: $DOCS_DB_HOST
         DB_PORT: $DOCS_DB_PORT
         DB_NAME: $DOCS_DB_NAME
         DB_USER: $DOCS_DB_USER
         DB_SSL: $DB_SSL

         LOG_LEVEL: DEBUG

      env_file:
         - $AUTH_FILE
         - services.env

      volumes:
         - ./logs/docs:/var/log/app
         - home-vol:/root

      ports:
         - "4001:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar

   queryset-manager:

      build: "views_queryset_manager/."
      image: viewsregistry.azurecr.io/prio-data/views_queryset_manager:2.0.0

      environment:
         DB_HOST: $QUERYSET_MANAGER_DB_HOST
         DB_PORT: $QUERYSET_MANAGER_DB_PORT
         DB_NAME: $QUERYSET_MANAGER_DB_NAME
         DB_USER: $QUERYSET_MANAGER_DB_USER
         DB_SSL: $DB_SSL

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4002:80"

      volumes:
         - ./logs/queryset-manager:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - job-manager

   job-manager:
      build: views_job_manager/.
      image: viewsregistry.azurecr.io/prio-data/views_job_manager:2.0.0

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4003:80"

      volumes:
         - ./logs/job-manager:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - router
         - ssl-sidecar

   router:
      build: views_router/.
      image: viewsregistry.azurecr.io/prio-data/views_router:3.0.1

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4004:80"

      volumes:
         - ./logs/router:/var/log/app
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - base-data-retriever
         - data-transformer

   base-data-retriever:
      build: base_data_retriever/.
      image: viewsregistry.azurecr.io/prio-data/base_data_retriever:2.0.1

      environment:
         DB_HOST: $BASE_DB_HOST
         DB_PORT: $BASE_DB_PORT
         DB_NAME: $BASE_DB_NAME
         DB_USER: $BASE_DB_USER
         DB_SSL: $DB_SSL

         DB_SCHEMA: $BASE_DB_SCHEMA

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4005:80"

      volumes:
         - ./logs/base-data-retriever:/var/log/app
         - home-vol:/root

      networks:
         - backend

   data-transformer:
      build: views_data_transformer/.
      image: viewsregistry.azurecr.io/prio-data/views_data_transformer:1.2.1

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4006:80"

      networks:
         - backend 

      volumes:
         - ./logs/data-transformer:/var/log/app

volumes:
   home-vol:

networks:
   backend:
      name: views_integration
