version: "3.9"
services:

   ssl-sidecar:
      image: prioreg.azurecr.io/prio-data/pg_ssl_sidecar:2.0.0
      env_file:
         - $AUTH_FILE
      volumes:
         - home-vol:/home_mnt

   storefront:
      build: views_storefront/.
      image: viewsregistry.azurecr.io/prio-data/views_storefront:1.0.1

      env_file:
         - services.env 

      ports:
         - "4000:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar
         - docs
         - queryset-manager

   docs:
      build: views_docs/.
      image: viewsregistry.azurecr.io/prio-data/views_docs:1.4.3

      environment:
         BASE_DATA_RETRIEVER_URL: http://base-data-retriever
         TRANSFORMER_URL: http://data-transformer
         FORWARDED_ALLOW_IPS: "*"
         SCRIPT_NAME: "/docs"

      env_file:
         - $AUTH_FILE
         - services.env

      volumes:
         - home-vol:/root

      ports:
         - "4001:80"
      networks:
         - backend

      depends_on:
         - ssl-sidecar

   queryset-manager:

      build: "views_queryset_manager/."
      image: viewsregistry.azurecr.io/prio-data/views_queryset_manager:1.1.3

      environment:
         FORWARDED_ALLOW_IPS: "*"
         SCRIPT_NAME: "/docs"

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4002:80"

      volumes:
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - job-manager

   job-manager:
      build: views_job_manager/.
      image: viewsregistry.azurecr.io/prio-data/views_job_manager:1.0.1

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4003:80"

      volumes:
         - home-vol:/root
      networks:
         - backend 

      depends_on:
         - router
         - ssl-sidecar

   router:
      build: views_router/.
      image: viewsregistry.azurecr.io/prio-data/views_router:1.0.0

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4004:80"

      volumes:
         - home-vol:/root

      networks:
         - backend 

      depends_on:
         - ssl-sidecar
         - base-data-retriever
         - data-transformer

   base-data-retriever:
      build: base_data_retriever/.
      image: viewsregistry.azurecr.io/prio-data/base_data_retriever:2.0.0

      environment:
         DB_HOST: $BASE_DB_HOST
         DB_PORT: $BASE_DB_PORT
         DB_NAME: $BASE_DB_NAME
         DB_USER: $BASE_DB_USER
         DB_SCHEMA: $BASE_DB_SCHEMA

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env

      ports:
         - "4005:80"

      volumes:
         - home-vol:/root

      networks:
         - backend

   data-transformer:
      build: views_data_transformer/.
      image: viewsregistry.azurecr.io/prio-data/views_data_transformer:1.1.0

      env_file:
         - $AUTH_FILE
         - services.env 
         - config.env


      ports:
         - "4006:80"

      networks:
         - backend 

volumes:
   home-vol:

networks:
   backend:
      name: views_integration
